### ISSUE TITLE
How to update FsLogix

### ISSUE THREAD

**Issue by DeepMalh44** [MicrosoftDocs/fslogix-docs#123]
Hello Team,
Reopened the below request again as there seems lack of documentation on how to Update FsLogix Agent on existing VM running old versions of FSLOGIX. Can someone please help here:

Documentation that needs update:  https://docs.microsoft.com/en-us/fslogix/install-ht

Following was the ask which remained unanswered

https://github.com/MicrosoftDocs/fslogix-docs/issues/111

**Comment by msft-jasonparker** [comment]
Hi @DeepMalh44, thanks for the feedback.  There are no separate instructions for upgrade installs versus new installs.  We are working on a complete doc refresh by end of year and we'll add a note about this at that time.

**Comment by SvenAelterman** [comment]
@msft-jasonparker But that is not "simple" without appropriate guidance. When "installing a new version," should the session hosts be drained of sessions? Should a reboot be expected after the install? Is it recommend to uninstall first?

When you're installing the new version on a host with an existing version and existing users, it seems to take a very long time for the installer the finish. It seems to be successful. If that lengthy (30+ minutes, I've observed) is expected, then that should be documented.

These are all reasonable questions that customers running an enterprise-scale service need to know rather than find out the hard way.
